### ISSUE TITLE
DTD does not match document type.

### ISSUE THREAD

**Issue by witiokz** [marek-stoj/NReadability#15]
Nreadability or other component is throwing exception, when incorrect Doctype is detected. It is incorrect behaviour. Tested web pags is:

http://rk19-bielefeld-mitte.de/survival/FM/02.htm

**Comment by witiokz** [comment]
Html parser is not very accurate. I think you should to switch to any another, because some additional html parsing is required before i can put downloaded html to NReadability.

NReadability fails if:
- html contains <!DOCTYPE doctype instead of <!DOCTYPE html
- some additional html exists after closing html tag.

**Comment by marek-stoj** [comment]
Current parser has worked fined for me.

Best Regards,
Marek Stój

## 

http://www.marekstoj.com
http://www.devmedia.pl

**Comment by witiokz** [comment]
I will post some link with incorrect behaviour with comments:

http://www.wikihow.com/Purify-Water - not all content is displayed.

http://wiid.twdb.state.tx.us/ims/wwm_drl/viewer.htm?TITLE=Texas&DISCL=0&APPNO=0&Box=382204:6850500:2614333:8052231 - exception is thown.

http://www.bt.cdc.gov/disasters/earthquakes/food.asp - not all content is download, around images.

http://www.grandpappy.info/wwater.htm - incorrect content parsing.

**Comment by witiokz** [comment]
Can i somehow affect html parsing, maybe tell nreadability skip some parsing or include any divs and etc ... I think, if you test nreadability with at least 1000 website, you understand the main problems.

**Comment by marek-stoj** [comment]
You are correct. NReadability is based on a date open-source version of
Readability. Now Readability is closed source but has an API.

Best Regards,
Marek Stój

## 

http://www.marekstoj.com
http://www.devmedia.pl

**Comment by witiokz** [comment]
I think one important thing is missing: exceptions. In general tool works great and thanks for excellent job, but some pages are so exceptional, that some parsing should be skipped: for example, some page http://www.someurl.com has images, which nreadability removes from extracted html, but i, for example, want to show images, so if some property could tell for nreadability to skip one or another rule,  it could be great.

**Comment by marek-stoj** [comment]
Yeap, it might be cool. But I won't have the time to do this myself. That's
why NReadability is an open-source project - feel free to contribute to it!

Best Regards,
Marek Stój

## 

http://www.marekstoj.com
http://www.devmedia.pl

**Comment by witiokz** [comment]
Yes, you are right.
