### ISSUE TITLE
Space between adjacent <a..>s ignored

### ISSUE THREAD

**Issue by buybackoff** [marek-stoj/NReadability#18]
Currently if I have adjacent links in original text  ...<a href=\"/f\">first</a> <a href=\"/s\">second</a>... the transcoder will remove the meaningful space between the links and will return ...<a href=\"/f\">first</a><a href=\"/s\">second</a>.... This is due to the option:

sgmlReader.WhitespaceHandling = WhitespaceHandling.None;

in the SgmlDomBuilder class. If changed to 

sgmlReader.WhitespaceHandling = WhitespaceHandling.Significant;

the space between the links stays after transcoding.

This will require some changes, e.g. in CollapseRedundantParagraphDivs method. However, current behavior make the text ugly and unreadable in some cases.

**Comment by marek-stoj** [comment]
Thanks for the info. It indeed fixes this specific issue. However, this change also breaks multiple unit tests and I don't have the time to look into it.
