### ISSUE TITLE
NuGet package requested

### ISSUE THREAD

**Issue by alexbeletsky** [marek-stoj/NReadability#2]
I've tried that and NReadability works pretty smooth. Thanks a lot for your effort, cool product :)

I would request, to package NReadability into NuGet package, so it's much more convinient to work, instead of building from sources.

**Comment by marek-stoj** [comment]
Hi,

thanks for the kind words. Creating NReadability NuGet packages is a great
idea - I'll try to get to it soon.

Best Regards,
Marek Stój

## 

http://www.marekstoj.com
http://www.devmedia.pl

On 14 March 2012 20:58, Alexander Beletsky <
reply@reply.github.com

**Comment by marek-stoj** [comment]
Done, here's the package: https://nuget.org/packages/NReadability
