### ISSUE TITLE
Calculating a page "score" for readability

### ISSUE THREAD

**Issue by nikhilsi** [marek-stoj/NReadability#4]
Hi Marek,
Given a URL, have you figured out a way to calulate how "readable" that page is (score 1 - 100; 100 being fully readable)? The safari browser on mac shows the Reader button (on the right side on the address bar) for some pages.

Thanks
Nikhil

**Comment by marek-stoj** [comment]
Hi, I didn't have need to do this.

**Comment by nikhilsi** [comment]
Hi Marek,
Can we add this feature? This is a very useful feature to have and can make this library more useful. Thanks for considering.

**Comment by marek-stoj** [comment]
Sure, I'd be happy if someone contributed this feature. But I won't have time to implement this myself any time soon, sorry.
