### ISSUE TITLE
Missing .cs files in solution

### ISSUE THREAD

**Issue by Gimdner** [marek-stoj/NReadability#6]
I'm not sure if I'm missing the obvious or not - but here goes:

I download the zipped file - unzip it
Navigate to "\marek-stoj-NReadability-4520e39\marek-stoj-NReadability-4520e39\Src\NReadability"
Open "NReadability.sln" in VS

I'm missing a total of 8 files - across two projects

NReadability:
TranscodingInput.cs
TranscodingResult.cs
WebTranscodingInput.cs
WebTranscodingResult.cs

NReadability.Tests:
FileBasedUrlFetcherStub.cs
NReadabilityTranscoderTests_Old.cs
NReadabilityWebTranscoderTests_Old.cs
SimpleUrlFetcherStub.cs

Can anyone point me in the right direction?

Many thanks in advance

**Comment by marek-stoj** [comment]
Yeap, sorry about that. I'll add those files tomorrow.

**Comment by Gimdner** [comment]
Thanks a bunch :-)

**Comment by marek-stoj** [comment]
Fixed.
