### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [marek-stoj/NReadability#9]
Hi, when I try to get the text from this link
http://www.morton-fraser.com/publications/articles/2450_is_there_an_obligation_on_a_bank_to_proceed_with_ancillary_elements_of_a_transaction_when_the_key_element_collapses
I get an error: 

Failure: System.NullReferenceException : Object reference not set to an instance of an object.

**Comment by marek-stoj** [comment]
Thanks for the feedback. Feel free to issue a pull request when you fix the issue :)
